"""Initial revision

Revision ID: 5bee9e3fe2ef
Revises: 
Create Date: 2022-09-08 17:29:40.791142

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5bee9e3fe2ef"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "channels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("retrieved_utc", sa.Integer(), nullable=False),
        sa.Column("updated_utc", sa.Integer(), nullable=False),
        sa.Column("min_message_id", sa.Integer(), nullable=False),
        sa.Column("max_message_id", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="TRUE", nullable=False),
        sa.Column("is_complete", sa.Boolean(), server_default="FALSE", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.Integer(), nullable=False),
        sa.Column("retrieved_utc", sa.Integer(), nullable=False),
        sa.Column("updated_utc", sa.Integer(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("messages")
    op.drop_table("channels")
    # ### end Alembic commands ###
