"""Add user channel relationship table

Revision ID: 6324cbc20fd0
Revises: 0da2318334c3
Create Date: 2022-11-07 04:56:21.422811

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "6324cbc20fd0"
down_revision = "0da2318334c3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "users", ["user_id"])
    op.create_table(
        "users_channels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["channels.channel_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_table("users_channels")
    # ### end Alembic commands ###
