"""Add user channel unique constraint

Revision ID: d3e449556763
Revises: 6324cbc20fd0
Create Date: 2022-11-07 05:04:44.806086

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "d3e449556763"
down_revision = "6324cbc20fd0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_users_channels_user_id_channel_id",
        "users_channels",
        ["user_id", "channel_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_users_channels_user_id_channel_id", "users_channels", type_="unique"
    )
    # ### end Alembic commands ###
